// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5fwlidiNcwVALwm21WD9XKTGWTvvV0Ns',
    appId: '1:653323756100:web:9ad579648acf635cb31211',
    messagingSenderId: '653323756100',
    projectId: 'flutter-projet-hache',
    authDomain: 'flutter-projet-hache.firebaseapp.com',
    storageBucket: 'flutter-projet-hache.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyk-HB_AmFg1zMXt4fokUZdVcMuv14It0',
    appId: '1:653323756100:android:dff0426209db4f3bb31211',
    messagingSenderId: '653323756100',
    projectId: 'flutter-projet-hache',
    storageBucket: 'flutter-projet-hache.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPdf3jGUdWRF_5x57jPW-IpGiAeYwmUy0',
    appId: '1:653323756100:ios:cbd230a1a4df4ea7b31211',
    messagingSenderId: '653323756100',
    projectId: 'flutter-projet-hache',
    storageBucket: 'flutter-projet-hache.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );
}
